[package]
name = "pathfinder"
version = "0.1.0"
authors = ["Valeryi Savich <relrin78@gmail.com>"]
repository = "https://github.com/OpenMatchmaking/pathfinder"
readme = "../README.md"
keywords = ["websocket", "kafka", "proxy"]
license = "BSD-3-Clause"

[dependencies]
clap = "2.26.2"
json = "0.11.9"
ws = "0.7.3"
yaml-rust = "0.3"

[dependencies.rdkafka]
version = "0.12.0"
features = ["ssl", "sasl"]
