[package]
name = "pathfinder"
version = "0.1.0"
authors = ["Valeryi Savich <relrin78@gmail.com>"]
repository = "https://github.com/OpenMatchmaking/pathfinder"
readme = "../README.md"
keywords = ["websocket", "kafka", "proxy"]
license = "BSD-3-Clause"

[dependencies]
structopt = "0.1.0"
structopt-derive = "0.1.0"
json = "0.11.9"
config = "0.7.0"
tokio-tungstenite = "0.4.0"
futures = "0.1.16"
tungstenite = "0.5.0"
tokio-core = "0.1.10"
uuid = { version = "0.5", features = ["v4"] }
redis-async = "0.0.6"
jsonwebtoken = "3"
serde = "1"
serde_derive = "1"

[dependencies.rdkafka]
version = "0.12.0"
features = ["ssl", "sasl"]
