[package]
name = "pathfinder"
version = "0.1.0"
authors = ["Valeryi Savich <relrin78@gmail.com>"]
repository = "https://github.com/OpenMatchmaking/pathfinder"
readme = "../README.md"
keywords = ["websocket", "rabbitmq", "proxy"]
license = "BSD-3-Clause"

[dependencies]
chrono = "0.4.0"
config = "0.7.0"
fern = { version = "0.5", features = ["colored"] }
futures = "0.1.17"
json = "0.11.12"
jsonwebtoken = "3"
lapin-futures = "0.10"
lapin-futures-rustls = "0.10.0"
lapin-futures-tls-api = "0.6.0"
redis-async = "0.0.6"
serde = "1"
serde_derive = "1"
structopt = "0.1"
structopt-derive = "0.1"
tls-api-stub = "0.1.12"
log = "0.4"
tokio-core = "0.1.10"
tokio-tungstenite = "0.4.0"
tungstenite = "0.5.0"
uuid = { version = "0.5", features = ["v4"] }
