version: "2"

networks:
  app-tier:
    driver: bridge

services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile_pathfinder
    volumes:
      - ./:/code/
    tty: true
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - app-tier

  redis:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      # - REDIS_PASSWORD=super_secret_password
    ports:
      - "6379:6379"

  redis_commander_ui:
    image: tenstartups/redis-commander
    command: --redis-host redis
    links:
      - redis:redis
    ports:
      - "8081:8081"

  rabbitmq:
    image: bitnami/rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_VHOST=vhost
    networks:
      - app-tier
