version: "3"

services:
  redis:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      # - REDIS_PASSWORD=super_secret_password
    ports:
      - "6379:6379"

  redis_commander_ui:
    image: tenstartups/redis-commander
    command: --redis-host redis
    links:
      - redis:redis
    ports:
      - "8081:8081"
